# -*- coding: utf-8 -*-
"""cohere_API.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u7c7VY_gLNRiNYEtCVN98ldzTzXkIwV0
"""

!pip install cohere

import cohere
co = cohere.Client('DGY7oZgN4dK8PExNW8BKfO6yNC3mKscV22D17OlZ')

tags = 'family, slide, candied apples, smiles'
start = 'Using the description provided, craft one question following an empahthizing comment to help draw out the nostalgic memories associated with this image. These questions are designed to be conversational and non-intrusive, intending to encourage the individual to reflect and share at their own pace, so refer to the past. Do not be too open ended or add explanations of why you generated that text. Description for photo: ' + tags

response = co.generate(
  model='command',
  prompt= start,
  max_tokens=150,
  temperature=0.9,
  k=0,
  stop_sequences=[],
  return_likelihoods='NONE')

conversation = []
conversation = [{"role":"Chatbot", "message": response[0].text}]

user_input = "It was for halloween! Lot's of fun!"

conversation.append({"role": "User", "message": user_input})

history = 'Continue the conversation naturally connecting from the chat_history'

print(conversation)

chat = co.chat(
  model='command',
  message= history,
  temperature=0.3,
  chat_history = conversation,
  connectors=[],
  documents=[]
)

conversation.append({"role": "Chatbot", "message":chat.text})

# until user_input == "end chat" => while loop

print(conversation)